argocdDestinationServer: https://kubernetes.default.svc

ingressHostname: 100.119.88.69.nip.io
ingressClass: traefik

githubOrgUrl: https://github.com/bernats-homelab
sourceRepoUrl: https://github.com/bernats-homelab/kubernetes-standard-services
