argocdDestinationServer: https://kubernetes.default.svc

ingressHostname: 192.168.1.50.nip.io

githubOrgUrl: https://github.com/bernats-homelab
sourceRepoUrl: https://github.com/bernats-homelab/kubernetes-standard-services
